### ISSUE TITLE
Get warranty status form

### ISSUE THREAD

**Issue by adnanhashmi09** [Mithra-Warranty/mithra_client#7]
Warranty details form is not built. It is similar to the registration form with minor changes. Find the design [here](https://www.figma.com/file/T27p5UGmmqTSYSdNXsbKeu/Mithra?node-id=181%3A2184).

**Comment by DecFox** [comment]
The issue tracker has been shifted to the Mithra repo: https://github.com/Mithra-Warranty/Mithra
The issue is replicated here: https://github.com/Mithra-Warranty/Mithra/issues/2, so this can be closed.
